os: linux
dist: xenial
language: shell
before_install:
  - chmod -R +x travis
jobs:
  include:
    - stage: electron
      services: docker
      script: ./travis/builder-wine.sh
    - language: node_js
      node_js: lts/*
      script: npm run release
    - os: osx
      osx_image: xcode11.3
      language: node_js
      node_js: lts/*
      script: npm run release
    - stage: docker-image
      services: docker
      script: ./travis/docker-image.sh
    - services: docker
      arch: arm64
      script: ./travis/docker-image.sh
    - stage: docker-manifest
      services: docker
      script: ./travis/docker-manifest.sh
branches:
  only:
  - master
